namespace: dandelion-testnet
#namePrefix: ptn0-
commonLabels:
  environment: production
  cardano_network: testnet
  cardano_node_type: haskell
  project_name: dandelion
commonAnnotations:
  note: free-apis!
generators:
- helm-chartInflator-postgres-ha.yaml
#- helm-chartInflator-kong.yaml
#- helm-chartInflator-konga.yaml
bases:
- ../../base/cardano-db-sync
- ../../base/cardano-explorer-api
- ../../base/cardano-graphql
- ../../base/cardano-hasura
- ../../base/cardano-node
- ../../base/cardano-rosetta
- ../../base/cardano-submit-api
- ../../base/ogmios
- ../../base/postgrest
- ../../base/postgres-ws
resources:
- resources/common-env-configmap.yaml
- resources/ingress.yaml

patches:
# FIXME: ugly hack to inject postgres read-only user
- path: patches/postgres-ha-secret.yaml
  target:
    kind: Secret
    name: init0-postgresql-ha-postgresql
- path: patches/genesis-image.yaml
  target:
    kind: Deployment
    name: cardano-graphql
# cardano-db-sync
- path: patches/cardano-db-sync-deployment-env.yaml
  target:
    kind: StatefulSet
    name: cardano-db-sync
- path: patches/cardano-db-sync-deployment-image.yaml
  target:
    kind: StatefulSet
    name: cardano-db-sync
# cardano-node
- path: patches/cardano-node-configmap.yaml
  target:
    kind: ConfigMap
    name: cardano-node
- path: patches/cardano-node-pvc.yaml
  target:
    kind: StatefulSet
    name: cardano-node
- path: patches/cardano-node-deployment-env.yaml
  target:
    kind: StatefulSet
    name: cardano-node
- path: patches/cardano-node-deployment-image.yaml
  target:
    kind: StatefulSet
    name: cardano-node
# cardano-rosetta
- path: patches/cardano-rosetta-deployment-image.yaml
  target:
    kind: Deployment
    name: cardano-rosetta
# cardano-submit-api
- path: patches/cardano-submit-api-deployment-env.yaml
  target:
    kind: Deployment
    name: cardano-submit-api
# cardano-explorer-api
- path: patches/cardano-explorer-api-deployment-env.yaml
  target:
    kind: Deployment
    name: cardano-explorer-api
# ogmios
- path: patches/ogmios-deployment-env.yaml
  target:
    kind: Deployment
    name: ogmios
